apiVersion: v1
kind: Template
metadata:
  name: prometheus-telemeter
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: online-registration-exporter
    labels:
      app: online-registration-exporter
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: online-registration-exporter
    template:
      metadata:
        labels:
          app: online-registration-exporter
      spec:
        containers:
        - name: online-registration-exporter
          image: ${IMAGE}:${IMAGE_TAG}
          resources:
            limits:
              cpu: 150m
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 50Mi
          ports:
          - containerPort: 9115
            name: http
            protocol: TCP
          volumeMounts:
          - name: online-registration-exporter-config
            mountPath: /etc/online-registration-exporter/
            readOnly: true
        volumes:
        - name: online-registration-exporter-config
          secret:
            defaultMode: 420
            secretName: online-registration-exporter-config
- apiVersion: v1
  kind: Secret
  metadata:
    name: online-registration-exporter-config
  data:
    config.yml: YXBpOgogIHVybDogaHR0cHM6Ly9leGFtcGxlLmNvbS9hcGkvCiAgdXNlcjogbXlfdXNlcgogIHRva2VuOiBteV90b2tlbgpwbGFuczoKLSBjbHVzdGVyQQotIGNsdXN0ZXJCCi0gY2x1c3RlckMK
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      prometheus: app-sre
    name: online-registration-exporter
  spec:
    endpoints:
      - port: http
    interval: 30s
    namespaceSelector:
      matchNames:
        - ${NAMESPACE}
    selector:
      matchLabels:
        app: online-registration-exporter
- apiVersion: v1
  kind: Service
  metadata:
    name: online-registration-exporter
    labels:
      app: online-registration-exporter
  spec:
    selector:
      app: online-registration-exporter
    ports:
    - name: http
      protocol: TCP
      port: 9115
      targetPort: 9115
parameters:
- name: IMAGE
  value: "quay.io/app-sre/online-registration-exporter"
  displayName: online-registration-exporter image
  description: online-registration-exporter container image. Defaults to quay.io/app-sre/online-registration-exporter
- name: IMAGE_TAG
  value: "latest"
  displayName: online-registration-exporter container image tag
- name: REPLICAS
  value: "1"
- name: NAMESPACE
  value: ""
